GET http://localhost:3000/api/todo
Accept: application/json

###
GET http://localhost:3000/api/todo/{{todoId}}
Accept: application/json

###
POST http://localhost:3000/api/todo
Content-Type: application/json

{
  "title": "A new Todo",
  "description": "A new Todo description",
  "completed": false,
  "priority": 2,
  "dueDate": "Thu Dec 08 2022 22:21:17 GMT+0530 (India Standard Time)"
}

###
PUT http://localhost:3000/api/todo/{{todoId}}
Content-Type: application/json

{
  "title": "An old Todo",
  "description": "An old Todo description",
  "completed": true,
  "priority": 1,
  "dueDate": "Thu Dec 08 2022 22:21:17 GMT+0530 (India Standard Time)"
}


###
DELETE http://localhost:3000/api/todo/{{todoId}}
